### ISSUE TITLE
Install documentation

### ISSUE THREAD

**Issue by speromelior** [TviNet/DeepLoc-2.0#1]
We are attempting to install this for the Institute, but having a lot of difficulty getting to the stage of a working utility either via Conda or GitHub.  The installations don't throw errors but don't appear to leave the application in a usable state.  Is there more documentation available somewhere that could help us?  We would prefer to use a pre-trained dataset if that is possible.

**Comment by teevee112** [comment]
Academic users can download the software from the downloads tab on https://services.healthtech.dtu.dk/services/DeepLoc-2.0/

**Comment by speromelior** [comment]
We have no problem downloading it, thank you.  It is the absence of install and user documentation that is preventing us from using it.

**Comment by teevee112** [comment]
Sorry for the confusion. This repository is only meant for training the models from scratch as described in the paper. 

The prediction webserver download is available at the link I shared above (have to do this because of license restrictions). 
This download should contain a README.md file which has the instructions for installing, running, and interpreting the outputs of the software.

Please let me know if that solves your issue.

**Comment by mat10d** [comment]
My research group has used deeploc extensively as a part of a pipeline that makes use of the prediction arm of deeploc only. Is there a way of installing the prediction arm so we can integrate it fully into our pipeline? I have downloaded the software but I am not sure the best way of doing this while also complying with license requirements. Thank you!

**Comment by teevee112** [comment]
If you download it via the academic license, you should be free to integrate it however you see fit. The only restriction might be for distributing it. As long as it is an independent component you could redirect to the downloads page as a prerequisite.
